spring:
  datasource:
    url: jdbc:mysql://localhost:3306/raf_vacuum
    username: root
    password: adikic3420rn
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day

logging:
  level:
    org.springframework.security: DEBUG

